### ISSUE TITLE
Show only white-listed roles for users at arsenals

### ISSUE THREAD

**Issue by bigdonabele** [jbrown215/TF146-scripts#2]
Currently the script will show all load outs scripted to the arsenal.  In order make selection easier and to clear up the UI on the user's end would like to be set so that users can only see loadouts available to them via their role in the server.

**Comment by jbrown215** [comment]
Can do. I investigated this a bit last night- the tricky bit is that the parameter that `addAction` exposes to gate the visibility of the action is a code string instead of a code block. This makes it a bit difficult, since it gets rid of any variables in local scope.

I had an idea to get around this: we can interpolate the whitelist array as a string into the String code argument we give to that parameter.

Another solution would be to store a whitelist variable in the namespace of the object and fetch it from there.
